"""sync_missing_columns

Revision ID: 567c2ba5cab9
Revises: 477951ad2918
Create Date: 2026-09-11 12:36:26.503232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""sync_missing_columns

Revision ID: 567c2ba5cab9
Revises: 477951ad2918
Create Date: 2026-09-11 12:36:26.503232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567c2ba5cab9'
down_revision: Union[str, Sequence[str], None] = '477951ad2918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'leave_requests' not in inspector.get_table_names():
        op.create_table('leave_requests',
        sa.Column('leave_id', sa.UUID(), nullable=False),
        sa.Column('driver_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('reviewed_by', sa.UUID(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('leave_id')
        )
    op.add_column('attendance', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('drivers_user_id_fkey'), 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('fuel_records', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.add_column('fuel_records', sa.Column('mileage', sa.Float(), nullable=True))
    op.add_column('fuel_records', sa.Column('refill_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'fuel_records', 'drivers', ['driver_id'], ['driver_id'], ondelete='SET NULL')
    op.add_column('shipments', sa.Column('expected_delivery_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trips', sa.Column('actual_distance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trips', sa.Column('route_type', sa.String(length=50), nullable=True))
    op.add_column('trips', sa.Column('planned_route', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('resolution_status', sa.String(length=20), nullable=False))
    op.add_column('vehicle_maintenance', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_maintenance', 'created_at')
    op.drop_column('vehicle_maintenance', 'resolution_status')
    op.drop_column('users', 'profile_picture')
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'planned_route')
    op.drop_column('trips', 'route_type')
    op.drop_column('trips', 'actual_distance')
    op.drop_column('trips', 'duration')
    op.drop_column('shipments', 'expected_delivery_time')
    op.drop_constraint(None, 'fuel_records', type_='foreignkey')
    op.drop_column('fuel_records', 'refill_date')
    op.drop_column('fuel_records', 'mileage')
    op.drop_column('fuel_records', 'driver_id')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(op.f('drivers_user_id_fkey'), 'drivers', 'users', ['user_id'], ['user_id'])
    op.drop_column('attendance', 'created_at')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
